In [43]:
import pandas as pd
df=pd.read_csv('weatherHistory.csv')
df[2:10:2]

,Formatted Date,Summary,Precip Type,Temperature,Apparent Temperature,Humidity,Wind Speed,Wind Bearing,Visibilit,Loud Cover,Pressure,Daily Summary
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
6,2006-04-01 06:00:00.000 +0200,Partly Cloudy,rain,7.733333,5.522222,0.95,12.3648,259.0,9.9820,0.0,1016.72,Partly cloudy throughout the day.
8,2006-04-01 08:00:00.000 +0200,Partly Cloudy,rain,10.822222,10.822222,0.82,11.3183,259.0,9.9820,0.0,1017.37,Partly cloudy throughout the day.

In [40]:
df['Temperature'].head(10).max()

13.77222222222222

In [41]:
df['Formatted Date'].head(10)[df['Wind Bearing']>200]

0    2006-04-01 00:00:00.000 +0200
1    2006-04-01 01:00:00.000 +0200
2    2006-04-01 02:00:00.000 +0200
3    2006-04-01 03:00:00.000 +0200
4    2006-04-01 04:00:00.000 +0200
5    2006-04-01 05:00:00.000 +0200
6    2006-04-01 06:00:00.000 +0200
7    2006-04-01 07:00:00.000 +0200
8    2006-04-01 08:00:00.000 +0200
9    2006-04-01 09:00:00.000 +0200
Name: Formatted Date, dtype: object

In [42]:
df['Temperature'].head(10).mean()

9.557222222222222

In [44]:
type(df['Temperature'])

pandas.core.series.Series

In [45]:
df.describe()

,Temperature,Apparent Temperature,Humidity,Wind Speed,Wind Bearing,Visibilit,Loud Cover,Pressure
count,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.0,96453.000000
mean,11.932678,10.855029,0.734899,10.810640,187.509232,10.347325,0.0,1003.235956
std,9.551546,10.696847,0.195473,6.913571,107.383428,4.192123,0.0,116.969906
min,-21.822222,-27.716667,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,4.688889,2.311111,0.600000,5.828200,116.000000,8.339800,0.0,1011.900000
50%,12.000000,12.000000,0.780000,9.965900,180.000000,10.046400,0.0,1016.450000
75%,18.838889,18.838889,0.890000,14.135800,290.000000,14.812000,0.0,1021.090000
max,39.905556,39.344444,1.000000,63.852600,359.000000,16.100000,0.0,1046.380000

In [57]:
df[df.Temperature>=38.90]

,Formatted Date,Summary,Precip Type,Temperature,Apparent Temperature,Humidity,Wind Speed,Wind Bearing,Visibilit,Loud Cover,Pressure,Daily Summary
12664,2007-07-19 16:00:00.000 +0200,Partly Cloudy,rain,38.983333,37.461111,0.18,8.9355,175.0,9.9820,0.0,1013.34,Partly cloudy starting in the afternoon.
12711,2007-07-20 15:00:00.000 +0200,Partly Cloudy,rain,38.983333,36.627778,0.14,12.7190,167.0,9.9820,0.0,1012.34,Partly cloudy starting in the afternoon contin...
12712,2007-07-20 16:00:00.000 +0200,Partly Cloudy,rain,38.983333,36.800000,0.15,15.4077,133.0,9.9820,0.0,1011.93,Partly cloudy starting in the afternoon contin...
12737,2007-07-21 17:00:00.000 +0200,Partly Cloudy,rain,39.588889,37.600000,0.15,12.2038,283.0,10.3523,0.0,1010.24,Partly cloudy starting in the morning continui...
12759,2007-07-22 15:00:00.000 +0200,Clear,rain,39.905556,37.538889,0.13,23.5865,250.0,9.9820,0.0,1007.55,Partly cloudy starting in the afternoon.

In [59]:
df[df.Temperature==df.Temperature.max()]

,Formatted Date,Summary,Precip Type,Temperature,Apparent Temperature,Humidity,Wind Speed,Wind Bearing,Visibilit,Loud Cover,Pressure,Daily Summary
12759,2007-07-22 15:00:00.000 +0200,Clear,rain,39.905556,37.538889,0.13,23.5865,250.0,9.982,0.0,1007.55,Partly cloudy starting in the afternoon.

In [62]:
df[['Formatted Date','Daily Summary','Temperature']][df.Temperature>=38.90]

,Formatted Date,Daily Summary,Temperature
12664,2007-07-19 16:00:00.000 +0200,Partly cloudy starting in the afternoon.,38.983333
12711,2007-07-20 15:00:00.000 +0200,Partly cloudy starting in the afternoon contin...,38.983333
12712,2007-07-20 16:00:00.000 +0200,Partly cloudy starting in the afternoon contin...,38.983333
12737,2007-07-21 17:00:00.000 +0200,Partly cloudy starting in the morning continui...,39.588889
12759,2007-07-22 15:00:00.000 +0200,Partly cloudy starting in the afternoon.,39.905556

In [63]:
df.set_index('Temperature',inplace=True)

In [64]:
df

,Formatted Date,Summary,Precip Type,Apparent Temperature,Humidity,Wind Speed,Wind Bearing,Visibilit,Loud Cover,Pressure,Daily Summary
Temperature,,,,,,,,,,,
9.472222,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
9.355556,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
9.377778,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
8.288889,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
8.755556,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...
26.016667,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,0.43,10.9963,31.0,16.1000,0.0,1014.36,Partly cloudy starting in the morning.
24.583333,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,0.48,10.0947,20.0,15.5526,0.0,1015.16,Partly cloudy starting in the morning.
22.038889,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,0.56,8.9838,30.0,16.1000,0.0,1015.66,Partly cloudy starting in the morning.
21.522222,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,0.60,10.5294,20.0,16.1000,0.0,1015.95,Partly cloudy starting in the morning.
20.438889,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,0.61,5.8765,39.0,15.5204,0.0,1016.16,Partly cloudy starting in the morning.

In [75]:
df.loc[22]

,Formatted Date,Summary,Precip Type,Apparent Temperature,Humidity,Wind Speed,Wind Bearing,Visibilit,Loud Cover,Pressure,Daily Summary
Temperature,,,,,,,,,,,
22.0,2006-09-27 12:00:00.000 +0200,Mostly Cloudy,rain,22.0,0.60,8.2915,222.0,9.9820,0.0,1013.22,Mostly cloudy throughout the day.
22.0,2007-08-11 09:00:00.000 +0200,Mostly Cloudy,rain,22.0,0.69,16.3737,158.0,11.2700,0.0,1007.26,Mostly cloudy throughout the day.
22.0,2007-07-24 04:00:00.000 +0200,Clear,rain,22.0,0.52,10.7065,151.0,15.8263,0.0,1004.79,Breezy and partly cloudy in the afternoon.
22.0,2007-05-05 11:00:00.000 +0200,Partly Cloudy,rain,22.0,0.60,7.9051,173.0,11.4471,0.0,1008.18,Foggy overnight.
22.0,2008-07-20 08:00:00.000 +0200,Clear,rain,22.0,0.66,5.8926,188.0,9.9820,0.0,1015.75,Partly cloudy starting in the afternoon contin...
22.0,2008-06-09 09:00:00.000 +0200,Partly Cloudy,rain,22.0,0.69,3.5420,328.0,9.9820,0.0,1018.40,Partly cloudy throughout the day.
22.0,2009-04-18 14:00:00.000 +0200,Mostly Cloudy,rain,22.0,0.38,13.7172,211.0,10.3684,0.0,1014.98,Foggy starting overnight continuing until morn...
22.0,2009-04-04 14:00:00.000 +0200,Partly Cloudy,rain,22.0,0.39,7.9373,30.0,10.3684,0.0,1018.71,Partly cloudy starting in the morning continui...
22.0,2010-07-10 08:00:00.000 +0200,Partly Cloudy,rain,22.0,0.68,12.4775,9.0,9.9820,0.0,1021.11,Partly cloudy starting in the morning continui...
22.0,2010-07-15 06:00:00.000 +0200,Clear,rain,22.0,0.88,3.0751,109.0,8.1305,0.0,1011.27,Partly cloudy starting in the morning continui...
22.0,2010-06-13 06:00:00.000 +0200,Clear,rain,22.0,0.82,8.3398,291.0,9.9820,0.0,1009.51,Partly cloudy starting overnight continuing un...
22.0,2011-06-05 07:00:00.000 +0200,Mostly Cloudy,rain,22.0,0.77,7.4060,169.0,9.9820,0.0,1014.52,Partly cloudy throughout the day.
22.0,2012-08-13 11:00:00.000 +0200,Partly Cloudy,rain,22.0,0.46,6.6815,322.0,11.3988,0.0,1016.03,Partly cloudy starting in the morning continui...
22.0,2012-10-15 15:00:00.000 +0200,Mostly Cloudy,rain,22.0,0.64,21.5257,149.0,11.2056,0.0,1008.09,Foggy in the morning.
22.0,2013-07-03 08:00:00.000 +0200,Partly Cloudy,rain,22.0,0.59,3.1395,129.0,9.9820,0.0,1017.26,Partly cloudy starting in the morning continui...
22.0,2013-06-12 11:00:00.000 +0200,Mostly Cloudy,rain,22.0,0.67,16.9372,342.0,11.4471,0.0,1013.87,Mostly cloudy throughout the day.
22.0,2013-05-02 21:00:00.000 +0200,Mostly Cloudy,rain,22.0,0.57,25.5185,249.0,11.1251,0.0,1013.19,Mostly cloudy starting in the morning.
22.0,2014-07-20 07:00:00.000 +0200,Clear,rain,22.0,0.76,1.6100,310.0,16.1000,0.0,1015.43,Partly cloudy starting in the morning.
22.0,2014-06-03 14:00:00.000 +0200,Mostly Cloudy,rain,22.0,0.43,1.5295,301.0,10.5777,0.0,1014.88,Mostly cloudy throughout the day.
22.0,2014-09-03 09:00:00.000 +0200,Overcast,rain,22.0,0.60,12.7351,39.0,16.1000,0.0,1010.52,Mostly cloudy throughout the day.
22.0,2015-08-31 07:00:00.000 +0200,Partly Cloudy,rain,22.0,0.69,10.8031,120.0,11.8979,0.0,1018.20,Partly cloudy until night.
22.0,2015-07-15 07:00:00.000 +0200,Partly Cloudy,rain,22.0,0.74,11.5437,289.0,16.1000,0.0,1017.21,Partly cloudy until night.
22.0,2015-06-12 07:00:00.000 +0200,Partly Cloudy,rain,22.0,0.77,4.7817,136.0,15.1340,0.0,1017.12,Partly cloudy throughout the day.
22.0,2016-06-27 21:00:00.000 +0200,Overcast,rain,22.0,0.74,15.5043,290.0,10.2557,0.0,1013.38,Mostly cloudy throughout the day.
22.0,2016-05-13 15:00:00.000 +0200,Breezy and Mostly Cloudy,rain,22.0,0.50,33.9710,220.0,9.9820,0.0,997.59,Partly cloudy throughout the day and breezy in...

In [76]:
df.reset_index(inplace=True)

In [79]:
df[2:10]

,Temperature,Formatted Date,Summary,Precip Type,Apparent Temperature,Humidity,Wind Speed,Wind Bearing,Visibilit,Loud Cover,Pressure,Daily Summary
2,9.377778,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,8.288889,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,8.755556,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
5,9.222222,2006-04-01 05:00:00.000 +0200,Partly Cloudy,rain,7.111111,0.85,13.9587,258.0,14.9569,0.0,1016.66,Partly cloudy throughout the day.
6,7.733333,2006-04-01 06:00:00.000 +0200,Partly Cloudy,rain,5.522222,0.95,12.3648,259.0,9.9820,0.0,1016.72,Partly cloudy throughout the day.
7,8.772222,2006-04-01 07:00:00.000 +0200,Partly Cloudy,rain,6.527778,0.89,14.1519,260.0,9.9820,0.0,1016.84,Partly cloudy throughout the day.
8,10.822222,2006-04-01 08:00:00.000 +0200,Partly Cloudy,rain,10.822222,0.82,11.3183,259.0,9.9820,0.0,1017.37,Partly cloudy throughout the day.
9,13.772222,2006-04-01 09:00:00.000 +0200,Partly Cloudy,rain,13.772222,0.72,12.5258,279.0,9.9820,0.0,1017.22,Partly cloudy throughout the day.